services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    buildCommand: ""
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://yourproject.onrender.com
